version: '3.8'

services:
  ibox-app:
    build: .
    container_name: ibox-management
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./accounts.json:/app/accounts.json
      - ./auto_login_config.json:/app/auto_login_config.json
      - ./proxy_list.json:/app/proxy_list.json
      - ./account_proxy_mapping.json:/app/account_proxy_mapping.json
      - ./status.json:/app/status.json
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    networks:
      - ibox-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: ibox-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - ibox-app
    networks:
      - ibox-network

networks:
  ibox-network:
    driver: bridge

volumes:
  data:
  logs: 